# Generated by Django 2.2.6 on 2019-11-07 11:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=mdeditor.fields.MDTextField(null=True),
        ),
    ]
