# Generated by Django 2.2.6 on 2020-05-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191107_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='CourseImage'),
            preserve_default=False,
        ),
    ]
